# Generated by Django 4.2.4 on 2023-09-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(default='', max_length=12)),
                ('Contact', models.CharField(default='', max_length=12)),
                ('Password', models.CharField(default='', max_length=12)),
                ('admin_id', models.CharField(default='', max_length=15)),
                ('status', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Application_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnrollmentId', models.CharField(default='', max_length=12)),
                ('Name', models.CharField(default='', max_length=12)),
                ('Email', models.CharField(default='', max_length=12)),
                ('App_Id', models.CharField(default='', max_length=12)),
                ('Dept_approval', models.CharField(default='', max_length=12)),
                ('Dept_Comment', models.CharField(default='', max_length=12)),
                ('TnP_approval', models.CharField(default='', max_length=12)),
                ('TnP_Comment', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_Id', models.CharField(default='', max_length=120)),
                ('Department_name', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnrollmentId', models.CharField(max_length=120)),
                ('Name', models.CharField(max_length=120)),
                ('fathers_name', models.CharField(max_length=120)),
                ('Address', models.CharField(max_length=120)),
                ('contact_Num', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=120)),
                ('Branch', models.CharField(max_length=120)),
                ('Noc_Count', models.CharField(default=0, max_length=120)),
            ],
        ),
    ]
