# Generated by Django 4.2.4 on 2023-09-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0002_student_password_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_table',
            name='Company',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='application_table',
            name='Role',
            field=models.CharField(default='', max_length=12),
        ),
    ]
