# Generated by Django 4.2.4 on 2023-09-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0003_application_table_company_application_table_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_table',
            name='Company',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='application_table',
            name='Dept_Comment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='application_table',
            name='Email',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='application_table',
            name='Name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application_table',
            name='Role',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='application_table',
            name='TnP_Comment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
