# Generated by Django 4.2.4 on 2023-10-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0006_application_table_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='Email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
