# Generated by Django 4.2.4 on 2023-11-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0008_application_table_app_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoDues_application_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnrollmentId', models.CharField(default='', max_length=12)),
                ('Name', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=35)),
                ('dept', models.CharField(default='', max_length=35)),
                ('Company', models.CharField(default='', max_length=35)),
                ('Role', models.CharField(default='', max_length=35)),
                ('App_Id', models.CharField(default='', max_length=12)),
                ('Dept_approval', models.CharField(default='', max_length=12)),
                ('Dept_Comment', models.CharField(default='', max_length=100)),
                ('TnP_approval', models.CharField(default='', max_length=12)),
                ('TnP_Comment', models.CharField(default='', max_length=100)),
                ('Lib_approval', models.CharField(default='', max_length=12)),
                ('Lib_Comment', models.CharField(default='', max_length=100)),
                ('Acc_approval', models.CharField(default='', max_length=12)),
                ('Acc_Comment', models.CharField(default='', max_length=100)),
                ('Hostle_approval', models.CharField(default='', max_length=12)),
                ('Hostle_Comment', models.CharField(default='', max_length=100)),
                ('App_Date', models.CharField(default='', max_length=100)),
                ('App_time', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
