# Generated by Django 4.2.4 on 2023-11-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0009_nodues_application_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodues_application_table',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='nodues_application_table',
            name='Role',
        ),
    ]
