# Generated by Django 4.2.4 on 2023-11-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0010_remove_nodues_application_table_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnrollmentId', models.CharField(default='', max_length=12)),
                ('Name', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
