# Generated by Django 4.2.4 on 2023-11-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0012_application_table_designation_reciever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_table',
            name='Role',
            field=models.CharField(default='-', max_length=35),
        ),
    ]
