# Generated by Django 5.0 on 2024-01-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0013_alter_application_table_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_table',
            name='offerletter',
            field=models.FileField(default='', upload_to='Static/pdfs'),
        ),
    ]
