# Generated by Django 5.0 on 2024-01-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0016_remove_application_table_offerletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_table',
            name='offerletter',
            field=models.FileField(default='', upload_to='pdfs/'),
        ),
    ]
