# Generated by Django 4.2.7 on 2024-02-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0022_alter_admins_dept_alter_application_table_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_table',
            name='date_dept_approval',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application_table',
            name='date_tnp_approval',
            field=models.CharField(default='', max_length=100),
        ),
    ]
