# Generated by Django 4.2.7 on 2024-03-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0025_department_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_enrollment_id', models.CharField(default='', max_length=15)),
                ('department', models.CharField(default='', max_length=35)),
                ('noc_approval_id', models.PositiveBigIntegerField(default='')),
                ('company_name', models.CharField(default='', max_length=35)),
                ('company_experience_rating', models.PositiveIntegerField(default=0)),
                ('work_environment_rating', models.PositiveIntegerField(default=0)),
                ('supervisor_rating', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('hr_name', models.EmailField(default='', max_length=35)),
                ('hr_contact_email', models.EmailField(default='', max_length=35)),
                ('hr_contact_number', models.CharField(blank=True, default='', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='admins',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='application_table',
            name='D_approved_by',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='application_table',
            name='Tnp_approved_by',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='admins',
            name='Password',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
