# Generated by Django 4.2.7 on 2024-03-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0026_internshipfeedback_admins_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipfeedback',
            name='company_experience_rating',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='internshipfeedback',
            name='noc_approval_id',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='internshipfeedback',
            name='supervisor_rating',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='internshipfeedback',
            name='work_environment_rating',
            field=models.CharField(default='', max_length=35),
        ),
    ]
