# Generated by Django 4.2.7 on 2024-04-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0027_alter_internshipfeedback_company_experience_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_table',
            name='allow_edit',
            field=models.CharField(default='', max_length=12),
        ),
    ]
