# Generated by Django 4.2.7 on 2024-04-30 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0029_bonafide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bonafide',
            new_name='BonafideModel',
        ),
    ]
