# Generated by Django 4.2.7 on 2024-04-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0030_rename_bonafide_bonafidemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonafidemodel',
            name='Branch',
            field=models.CharField(default='', max_length=20),
        ),
    ]
