# Generated by Django 4.2.7 on 2024-05-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0031_bonafidemodel_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafidemodel',
            name='Branch',
            field=models.CharField(default='', max_length=50),
        ),
    ]
