# Generated by Django 4.2.7 on 2024-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0032_alter_bonafidemodel_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='programmme',
            field=models.CharField(default='', max_length=20),
        ),
    ]
