# Generated by Django 4.2.7 on 2024-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0033_department_programmme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=120)),
                ('EnrollmentId', models.CharField(default='', max_length=120)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Department', models.CharField(default='', max_length=120)),
                ('Phone', models.CharField(default='', max_length=15)),
                ('Apply', models.CharField(default='Yes', max_length=10)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(default='', max_length=10)),
                ('Course', models.CharField(default='', max_length=50)),
                ('Branch', models.CharField(default='', max_length=120)),
                ('RateFaculty', models.IntegerField(default=0)),
                ('TeachingMethods', models.TextField(default='')),
                ('LearningResources', models.TextField(default='')),
                ('SyllabusCompletion', models.TextField(default='')),
                ('CourseRelevance', models.TextField(default='')),
                ('TeacherPreparedness', models.TextField(default='')),
                ('CourseOutcomes', models.TextField(default='')),
                ('SoftSkills', models.TextField(default='')),
                ('InternshipsSupport', models.TextField(default='')),
                ('StudentOrgs', models.TextField(default='')),
                ('CurricularExtracurricular', models.TextField(default='')),
                ('Quizzes', models.TextField(default='')),
                ('EvaluationFairness', models.TextField(default='')),
                ('LibraryResources', models.TextField(default='')),
                ('CurriculumFlexibility', models.TextField(default='')),
                ('NPTELMOOCs', models.TextField(default='')),
                ('FullSemesterInternship', models.TextField(default='')),
                ('TrainingPlacement', models.TextField(default='')),
                ('SportsFacilities', models.TextField(default='')),
                ('HostelMaintenance', models.TextField(default='')),
                ('OverallRating', models.IntegerField(default=0)),
                ('FinalFeedback', models.TextField(default='')),
                ('AppDate', models.DateField(auto_now_add=True)),
                ('AppTime', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
