# Generated by Django 4.2.7 on 2024-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0034_exitsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodues_application_table',
            name='account_holder_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nodues_application_table',
            name='account_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nodues_application_table',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nodues_application_table',
            name='caution_money',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='nodues_application_table',
            name='dob',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nodues_application_table',
            name='fees_due',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='nodues_application_table',
            name='hostel',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='nodues_application_table',
            name='ifsc_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nodues_application_table',
            name='passOutYear',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='nodues_application_table',
            name='project_report',
            field=models.CharField(default='', max_length=3),
        ),
    ]
