# Generated by Django 4.2.7 on 2024-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0036_remove_exitsurvey_finalfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodues_application_table',
            name='Exam_Comment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='nodues_application_table',
            name='Exam_approval',
            field=models.CharField(default='', max_length=12),
        ),
    ]
