# Generated by Django 4.2.7 on 2024-06-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0038_alter_graduated_enrollmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='signature',
            field=models.FileField(default='', upload_to='static/'),
        ),
    ]
