# Generated by Django 4.2.7 on 2024-06-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0039_admins_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='signature',
            field=models.CharField(max_length=255),
        ),
    ]
