# Generated by Django 4.2.7 on 2024-06-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0041_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Email_personal',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
