# Generated by Django 4.2.7 on 2024-07-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0043_nodues_application_table_dept_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitsurvey',
            name='offer_letter_1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='exitsurvey',
            name='offer_letter_2',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='exitsurvey',
            name='offer_letter_3',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='exitsurvey',
            name='offer_letter_4',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='exitsurvey',
            name='offer_letter_5',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
