# Generated by Django 4.2.7 on 2024-07-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0044_exitsurvey_offer_letter_1_exitsurvey_offer_letter_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitsurvey',
            name='offer_letter_1',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
    ]
