# Generated by Django 4.2.7 on 2024-07-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0045_alter_exitsurvey_offer_letter_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitsurvey',
            name='AdmissionLetter',
            field=models.FileField(blank=True, null=True, upload_to='higher_education_documents/'),
        ),
        migrations.AlterField(
            model_name='exitsurvey',
            name='FinalSemesterInternshipDoc',
            field=models.FileField(blank=True, null=True, upload_to='final_semester_documents/'),
        ),
        migrations.AlterField(
            model_name='exitsurvey',
            name='GateScorecard',
            field=models.FileField(blank=True, null=True, upload_to='gate_scorecards/'),
        ),
        migrations.AlterField(
            model_name='exitsurvey',
            name='OutsideJobLetter',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
        migrations.AlterField(
            model_name='exitsurvey',
            name='ScoreCardsAll',
            field=models.FileField(blank=True, null=True, upload_to='entrance_exam_scorecards/'),
        ),
        migrations.AlterField(
            model_name='exitsurvey',
            name='offer_letter_2',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
        migrations.AlterField(
            model_name='exitsurvey',
            name='offer_letter_3',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
        migrations.AlterField(
            model_name='exitsurvey',
            name='offer_letter_4',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
        migrations.AlterField(
            model_name='exitsurvey',
            name='offer_letter_5',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
    ]
