# Generated by Django 4.2.7 on 2024-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0046_alter_exitsurvey_admissionletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitsurvey',
            name='StipendDocProof',
            field=models.TextField(default=''),
        ),
    ]
