# Generated by Django 4.2.7 on 2024-07-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nocrest', '0049_alter_admins_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Displayname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
